ci: Temporarily disable openindiana
```
  + pkg install developer/versioning/git archiver/gnu-tar test/jq runtime/nodejs runtime/python developer/clang-21 developer/gcc-14 developer/lang/rustc
   Startup: Refreshing catalog openindiana.org ... Done
   Startup: Caching catalogs ... Done
  Planning: Solver setup ...
  pkg install: No matching version of developer/gcc-14 can be installed:
    Reject:  pkg://openindiana.org/developer/gcc-14@14.3.0-2026.0.0.1
    Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-2026.0.0.32718
  No matching version of developer/lang/rustc can be installed:
    Reject:  pkg://openindiana.org/developer/lang/rustc@1.95.0-2026.0.0.0
    Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-2026.0.0.32718
  No matching version of developer/versioning/git can be installed:
    Reject:  pkg://openindiana.org/developer/versioning/git@2.54.0-2026.0.0.0
    Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-2026.0.0.32718
```

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -520,54 +520,55 @@ jobs:
             git config --global --add safe.directory "$(pwd)"
             tools/ci/tidy-show-deps.sh
             tools/ci/tidy.sh
-  test-tidy-vm-openindiana:
-    runs-on: ubuntu-24.04
-    timeout-minutes: 60
-    steps:
-      - uses: taiki-e/checkout-action@v1
-      - uses: vmactions/openindiana-vm@0544593284f5c837f637097e278df86bf5bbab1e # v1.0.7
-        with:
-          envs: CARGO_INCREMENTAL CARGO_NET_RETRY CARGO_TERM_COLOR RUST_BACKTRACE RUST_TEST_THREADS RUSTDOCFLAGS RUSTFLAGS RUSTUP_MAX_RETRIES TIDY_EXPECTED_MARKDOWN_FILE_COUNT TIDY_EXPECTED_RUST_FILE_COUNT TIDY_EXPECTED_CLANG_FORMAT_FILE_COUNT TIDY_EXPECTED_PRETTIER_FILE_COUNT TIDY_EXPECTED_TOML_FILE_COUNT TIDY_EXPECTED_SHELL_FILE_COUNT TIDY_EXPECTED_DOCKER_FILE_COUNT
-          usesh: true
-          copyback: false
-          run: |
-            # illumos sh has no -E
-            # shellcheck disable=SC3040
-            set -Ceuxo pipefail
-            # shellcheck disable=SC3009
-            retry() {
-              for i in {1..10}; do
-                if "$@"; then
-                  return 0
-                else
-                  sleep "${i}"
-                fi
-              done
-              "$@"
-            }
-            # Install Rust from package manager due to "ld.so.1: rustup-init: fatal: libgcc_s.so.1: open failed: No such file or directory" error.
-            # Refs: https://pkg.openindiana.org/hipster/en/index.shtml
-            retry pkg install developer/versioning/git archiver/gnu-tar test/jq runtime/nodejs runtime/python developer/clang-21 developer/gcc-14 developer/lang/rustc
-            retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 -o bootstrap.tar.gz https://pkgsrc.SmartOS.org/packages/SmartOS/bootstrap/bootstrap-2024Q4-x86_64.tar.gz
-            tar xzpf bootstrap.tar.gz -C /
-            export PATH="/opt/local/sbin:/opt/local/bin:${PATH}"
-            # Refs: https://pkgsrc.smartos.org/packages/SmartOS/2024Q4/x86_64/All/
-            retry pkgin -y install shfmt shellcheck
-            export PATH="${HOME}/.cargo/bin:${PATH}"
-            # Install from source due to "libgcc_s.so.1: open failed: No such file or directory" error.
-            cargo install parse-dockerfile --debug
-            rm -rf -- /tmp/cargo-install* # cargo install artifacts
-            # Failed to install due to jemalloc build error.
-            # Install uv from source is very slow.
-            # cargo install uv --debug --locked --git https://github.com/taiki-e/uv.git --branch dev
-            # rm -rf -- /tmp/cargo-install* # cargo install artifacts
-            # Failed to install due to jemalloc build error.
-            # Install zizmor from source is very slow.
-            # cargo install zizmor --debug --locked --git https://github.com/taiki-e/zizmor.git --branch dev
-            # rm -rf -- /tmp/cargo-install* # cargo install artifacts
-            git config --global --add safe.directory "$(pwd)"
-            # min-release-age and allow-git requires npm 11.10+
-            npm --version
-            npm install --location=global npm@11.11.0
-            tools/ci/tidy-show-deps.sh
-            tools/ci/tidy.sh
+  # TODO: error on pkg install
+  # test-tidy-vm-openindiana:
+  #   runs-on: ubuntu-24.04
+  #   timeout-minutes: 60
+  #   steps:
+  #     - uses: taiki-e/checkout-action@v1
+  #     - uses: vmactions/openindiana-vm@0544593284f5c837f637097e278df86bf5bbab1e # v1.0.7
+  #       with:
+  #         envs: CARGO_INCREMENTAL CARGO_NET_RETRY CARGO_TERM_COLOR RUST_BACKTRACE RUST_TEST_THREADS RUSTDOCFLAGS RUSTFLAGS RUSTUP_MAX_RETRIES TIDY_EXPECTED_MARKDOWN_FILE_COUNT TIDY_EXPECTED_RUST_FILE_COUNT TIDY_EXPECTED_CLANG_FORMAT_FILE_COUNT TIDY_EXPECTED_PRETTIER_FILE_COUNT TIDY_EXPECTED_TOML_FILE_COUNT TIDY_EXPECTED_SHELL_FILE_COUNT TIDY_EXPECTED_DOCKER_FILE_COUNT
+  #         usesh: true
+  #         copyback: false
+  #         run: |
+  #           # illumos sh has no -E
+  #           # shellcheck disable=SC3040
+  #           set -Ceuxo pipefail
+  #           # shellcheck disable=SC3009
+  #           retry() {
+  #             for i in {1..10}; do
+  #               if "$@"; then
+  #                 return 0
+  #               else
+  #                 sleep "${i}"
+  #               fi
+  #             done
+  #             "$@"
+  #           }
+  #           # Install Rust from package manager due to "ld.so.1: rustup-init: fatal: libgcc_s.so.1: open failed: No such file or directory" error.
+  #           # Refs: https://pkg.openindiana.org/hipster/en/index.shtml
+  #           retry pkg install developer/versioning/git archiver/gnu-tar test/jq runtime/nodejs runtime/python developer/clang-21 developer/gcc-14 developer/lang/rustc
+  #           retry curl --proto '=https' --tlsv1.2 -fsSL --retry 10 -o bootstrap.tar.gz https://pkgsrc.SmartOS.org/packages/SmartOS/bootstrap/bootstrap-2024Q4-x86_64.tar.gz
+  #           tar xzpf bootstrap.tar.gz -C /
+  #           export PATH="/opt/local/sbin:/opt/local/bin:${PATH}"
+  #           # Refs: https://pkgsrc.smartos.org/packages/SmartOS/2024Q4/x86_64/All/
+  #           retry pkgin -y install shfmt shellcheck
+  #           export PATH="${HOME}/.cargo/bin:${PATH}"
+  #           # Install from source due to "libgcc_s.so.1: open failed: No such file or directory" error.
+  #           cargo install parse-dockerfile --debug
+  #           rm -rf -- /tmp/cargo-install* # cargo install artifacts
+  #           # Failed to install due to jemalloc build error.
+  #           # Install uv from source is very slow.
+  #           # cargo install uv --debug --locked --git https://github.com/taiki-e/uv.git --branch dev
+  #           # rm -rf -- /tmp/cargo-install* # cargo install artifacts
+  #           # Failed to install due to jemalloc build error.
+  #           # Install zizmor from source is very slow.
+  #           # cargo install zizmor --debug --locked --git https://github.com/taiki-e/zizmor.git --branch dev
+  #           # rm -rf -- /tmp/cargo-install* # cargo install artifacts
+  #           git config --global --add safe.directory "$(pwd)"
+  #           # min-release-age and allow-git requires npm 11.10+
+  #           npm --version
+  #           npm install --location=global npm@11.11.0
+  #           tools/ci/tidy-show-deps.sh
+  #           tools/ci/tidy.sh
